//global using Modelbuilder.ViewModels;
//global using Syncfusion.Windows.PdfViewer;
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
//global using CommunityToolkit.Mvvm.ComponentModel;
global using DataFormats = System.Windows.DataFormats;
global using MessageBox = System.Windows.MessageBox;
global using Modelbouwer.Helper;
//global using Modelbouwer.Model;
global using Modelbouwer.View;
global using MySql.Data.MySqlClient;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Panel = System.Windows.Controls.Panel;
global using static Modelbouwer.App;
global using System.Collections.ObjectModel;
global using System.Data;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Security.Cryptography;
global using System.Text.RegularExpressions;
global using System.Text;
global using System.Windows.Controls.Primitives;
global using System.Windows.Controls;
global using System.Windows.Forms;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows;
global using TextBox = System.Windows.Controls.TextBox;
